title: "Josh Rowey"
description: "Primary School ICT Technician | Tech Enthusiast | Open Source Contributor"
baseurl: ""
url: "https://mrrowey.github.io" # Change this to your GitHub Pages URL if different
